GaloGroupApp/Areas/Admin/Controllers/HeaderTopicsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GaloGroup.Domain.DBModel;

namespace GaloGroupApp.Areas.Admin.Controllers
{
    public class HeaderTopicsController : Controller
    {
        private GaloGroupDB db = new GaloGroupDB();

        // GET: Admin/HeaderTopics
        public async Task<ActionResult> Index()
        {
            return View(await db.HeaderTopics.ToListAsync());
        }

        // GET: Admin/HeaderTopics/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HeaderTopic headerTopic = await db.HeaderTopics.FindAsync(id);
            if (headerTopic == null)
            {
                return HttpNotFound();
            }
            return View(headerTopic);
        }

        // GET: Admin/HeaderTopics/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/HeaderTopics/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "id,TrainingCourseId,HeadingTopic")] HeaderTopic headerTopic)
        {
            if (ModelState.IsValid)
            {
                db.HeaderTopics.Add(headerTopic);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(headerTopic);
        }

        // GET: Admin/HeaderTopics/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HeaderTopic headerTopic = await db.HeaderTopics.FindAsync(id);
            if (headerTopic == null)
            {
                return HttpNotFound();
            }
            return View(headerTopic);
        }

        // POST: Admin/HeaderTopics/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "id,TrainingCourseId,HeadingTopic")] HeaderTopic headerTopic)
        {
            if (ModelState.IsValid)
            {
                db.Entry(headerTopic).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(headerTopic);
        }

        // GET: Admin/HeaderTopics/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HeaderTopic headerTopic = await db.HeaderTopics.FindAsync(id);
            if (headerTopic == null)
            {
                return HttpNotFound();
            }
            return View(headerTopic);
        }

        // POST: Admin/HeaderTopics/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            HeaderTopic headerTopic = await db.HeaderTopics.FindAsync(id);
            db.HeaderTopics.Remove(headerTopic);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GaloGroupApp/Areas/Admin/Controllers/ProductsController.cs
using GaloGroup.Domain.DBModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GaloGroupApp.Areas.Admin.Controllers
{
    public class ProductsController : Controller
    {
        private GaloGroupDB db = new GaloGroupDB();
        // GET: Admin/Products
        public ActionResult Index()
        {
                 
            return View(db.Products.ToList());
        }

        // GET: Admin/Products/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Admin/Products/Create
        public ActionResult ProductsWindow()
        {
            return View();
        }

        // POST: Admin/Products/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Admin/Products/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Admin/Products/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Admin/Products/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Admin/Products/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

GaloGroupApp/Areas/Admin/Controllers/TeachersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GaloGroup.Domain.DBModel;

namespace GaloGroupApp.Areas.Admin.Controllers
{
    public class TeachersController : Controller
    {
        private GaloGroupDB db = new GaloGroupDB();

        // GET: Admin/Teachers
        public async Task<ActionResult> Index()
        {
            return View(await db.Teachers.ToListAsync());
        }

        // GET: Admin/Teachers/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Teacher teacher = await db.Teachers.FindAsync(id);
            if (teacher == null)
            {
                return HttpNotFound();
            }
            return View(teacher);
        }

        // GET: Admin/Teachers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/Teachers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,TeacherFullName,NationalNo,PhoneNumber,MobileNumber,Address,Biography")] Teacher teacher)
        {
            if (ModelState.IsValid)
            {
                db.Teachers.Add(teacher);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(teacher);
        }

        // GET: Admin/Teachers/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Teacher teacher = await db.Teachers.FindAsync(id);
            if (teacher == null)
            {
                return HttpNotFound();
            }
            return View(teacher);
        }

        // POST: Admin/Teachers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,TeacherFullName,NationalNo,PhoneNumber,MobileNumber,Address,Biography")] Teacher teacher)
        {
            if (ModelState.IsValid)
            {
                db.Entry(teacher).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(teacher);
        }

        // GET: Admin/Teachers/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Teacher teacher = await db.Teachers.FindAsync(id);
            if (teacher == null)
            {
                return HttpNotFound();
            }
            return View(teacher);
        }

        // POST: Admin/Teachers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Teacher teacher = await db.Teachers.FindAsync(id);
            db.Teachers.Remove(teacher);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GaloGroupApp/Areas/Admin/Controllers/TrainingCoursesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GaloGroup.Domain.DBModel;

namespace GaloGroupApp.Areas.Admin.Controllers
{
    public class TrainingCoursesController : Controller
    {
        private GaloGroupDB db = new GaloGroupDB();

        // GET: Admin/TrainingCourses
        public async Task<ActionResult> Index()
        {
            return View(await db.TrainingCourses.ToListAsync());
        }

        // GET: Admin/TrainingCourses/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TrainingCourse trainingCourse = await db.TrainingCourses.FindAsync(id);
            if (trainingCourse == null)
            {
                return HttpNotFound();
            }
            return View(trainingCourse);
        }

        // GET: Admin/TrainingCourses/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/TrainingCourses/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,TrainingCourseTitle,CategoryId")] TrainingCourse trainingCourse)
        {
            if (ModelState.IsValid)
            {
                db.TrainingCourses.Add(trainingCourse);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(trainingCourse);
        }

        // GET: Admin/TrainingCourses/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TrainingCourse trainingCourse = await db.TrainingCourses.FindAsync(id);
            if (trainingCourse == null)
            {
                return HttpNotFound();
            }
            return View(trainingCourse);
        }

        // POST: Admin/TrainingCourses/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,TrainingCourseTitle,CategoryId")] TrainingCourse trainingCourse)
        {
            if (ModelState.IsValid)
            {
                db.Entry(trainingCourse).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(trainingCourse);
        }

        // GET: Admin/TrainingCourses/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TrainingCourse trainingCourse = await db.TrainingCourses.FindAsync(id);
            if (trainingCourse == null)
            {
                return HttpNotFound();
            }
            return View(trainingCourse);
        }

        // POST: Admin/TrainingCourses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            TrainingCourse trainingCourse = await db.TrainingCourses.FindAsync(id);
            db.TrainingCourses.Remove(trainingCourse);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GaloGroupApp/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body style="background-image:url('../../../../Content/Pic/77-2.jpg')">

    <div class="navbar navbar-inverse navbar-fixed-top" style="        height: 100px;
 
        background-image: url('../../../../Content/Pic/Inked24920_LI3.jpg');
        background-repeat: no-repeat;
        background-size: cover ">
        @*   <div class="navbar navbar-inverse navbar-fixed-top">*@
        <div class="container">
            <div class="navbar-header navbar-left">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("گالو گروپ", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                <img src="~/Content/Pic/77-3.jpg" />
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container text-center" style="margin-top:50px;">
        <div class="row content">
            <div class="container col-sm-10 bg-danger" style="margin-top:10px">
                @RenderBody()
            </div>

            <div class="col-sm-2 sidenav " style="margin-top:10px">
                <div class="panel-group panel" style="background-color:#feaeae" id="accordion" role="tablist" aria-multiselectable="true">
                    <div class="panel" style="background-color:#feaeae">
                        <div style="background-color:#bd1515" class="panel-heading" role="tab" id="headingTwo">
                            <h4 class="panel-title">
                                <a style="color:white" class="collapsed " role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="false" aria-controls="collapseTwo">
                                    آموزش
                                </a>
                            </h4>
                        </div>
                        <div id="collapseOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
                            <ul class="nav nav-pills nav-stacked alert-danger ">
                                <li role="presentation" class="">@Html.ActionLink("گروه آموزشی", "Index", "TrainingCategories", new { area = "Admin" }, null)</li>
                                <li role="presentation" class="">@Html.ActionLink("دوره های آموزش", "Index", "TrainingCourses", new { area = "Admin" }, null)</li>
                                <li role="presentation" class="">@Html.ActionLink("سرفصل دوره ها", "Index", "HeaderTopics", new { area = "Admin" }, null)</li>
                                <li role="presentation" class="">@Html.ActionLink("مدرسین", "Index", "Teachers", new { area = "Admin" }, null)</li>
                                <li role="presentation" class="">@Html.ActionLink("تقویم آموزشی", "Index", "EducationalCalendars", new { area = "Admin" }, null)</li>

                            </ul>
                        </div>

                    </div>

                    <div class="panel" style="background-color:#feaeae">
                        <div class="panel-heading" style="background-color:#bd1515" role="tab" id="headingThree">
                            <h4 class="panel-title">
                                <a style="color:white" class="collapsed " role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                                    محصولات
                                </a>
                            </h4>
                        </div>
                        <div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
                            <ul class="nav nav-pills nav-stacked alert-danger ">
                                <li role="presentation" class="">@Html.ActionLink("انواع محصولات", "Index", "TrainingCategories", new { area = "Admin" }, null)</li>
                                <li role="presentation" class="">@Html.ActionLink("لیست محصولات", "Index", "Products", new { area = "Admin"} , null )</li>
                            </ul>
                        </div>
                    </div>



                    <div class="panel" style="background-color:#feaeae">
                        <div style="background-color:#bd1515" class="panel-heading" role="tab" id="headingTwo">
                            <h4 class="panel-title">
                                <a style="color:white" class="collapsed " role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                                    عملیات
                                </a>
                            </h4>
                        </div>
                        <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
                            <ul class="nav nav-pills nav-stacked alert-info ">
                                <li role="presentation"><a href="#">Home</a></li>

                                <li role="presentation"><a href="#">Profile</a></li>

                                <li role="presentation"><a href="#">Messages</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>